// //////////////////////////////////////////////////
// // ✅ 2-2. Not Found Routes
// // 네비게이션 바 구현
// // Not Found Routes
// // not-found.tsx
// // usePathname

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

// //////////////////////////////////////////////////
// // ✅ 2-7. Layouts
// // 레이아웃 시스템
// // 레이아웃 시스템에 대해서 배워야 하는 이유는
// // application을 빌드할 때 재사용하는 요소(element)들이 있기 때문이다.

// import Navigation from '../components/navigation';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navigation />
//         {children}
//       </body>
//     </html>
//   );
// }

// {
//   // <Layout>
//   //   <AboutUsLayout>
//   //     <SalesLayout>
//   //       <Sales />
//   //     </SalesLayout>
//   //   </AboutUsLayout>
//   // </Layout>;
// }

// //////////////////////////////////////////////////
// // ✅ 2-8. Metadata
// // route groups을 사용하여 route들을 정리하는 방법
// // metadata object

// import Navigation from '../components/navigation';
// import { Metadata } from 'next';

// // 🔶 모든 레이아웃에 적용 됨
// // 🔶 메타데이터에 대한 템플릿 생성 가능
// export const metadata: Metadata = {
//   title: {
//     template: '%s | Next Movies',
//     default: 'Next Movies',
//   },
//   description: 'The best movies on th best frameworks',
// };

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navigation />
//         {children}
//       </body>
//     </html>
//   );
// }

//////////////////////////////////////////////////
// ✅ 4-1. CSS Modules

import '../styles/global.css';
import Navigation from '../components/navigation';
import { Metadata } from 'next';

// 메타데이터에 대한 템플릿 생성 가능
export const metadata: Metadata = {
  title: {
    template: '%s | Next Movies',
    default: 'Next Movies',
  },
  description: 'The best movies on th best frameworks',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
