//////////////////////////////////////////////////
// ✅ 2-2. Not Found Routes
// 네비게이션 바 구현
// Not Found Routes
// not-found.tsx
// usePathname

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
