//////////////////////////////////////////////////
// ✅ 2-1. Defining Routes
// NextJS 애플리케이션에서 새로운 페이지 만드는 방법

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
